/* The following code was generated by JFlex 1.4.3 on 12/3/21 00:07 */

package proyectocompiladores;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/3/21 00:07 from the specification file
 * <tt>C:/Users/willi/OneDrive/Documents/NetBeansProjects/Proyecto_Compiladores_I-master/src/proyectocompiladores/Analizador_Sintactico.flex</tt>
 */
public class Analizador_Sintactico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 12,  0,  0, 10,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    10,  0, 11,  0,  0,  0, 15, 13, 14, 14,  9,  9, 14,  1, 14,  9, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0,  0,  4,  4,  4,  0, 
     0, 31, 22, 24,  8, 25, 28, 30, 34, 16,  3, 37, 23,  6, 29,  7, 
    17,  3, 18, 26, 19, 21, 36, 33, 35, 32,  3,  0,  0,  0,  9,  3, 
     0, 31, 22, 24,  8, 25, 28, 30, 34, 16,  3, 37, 23,  6, 29,  7, 
    17,  3, 18, 20, 19, 27, 36, 33, 35, 32,  3, 14,  5, 14,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\4\3\1\5\1\6"+
    "\3\7\1\10\20\3\1\11\1\3\1\11\1\3\1\11"+
    "\1\3\1\11\11\3\1\11\1\3\1\0\1\12\1\11"+
    "\5\3\1\11\23\3\1\11\3\3\1\11\1\3\1\11"+
    "\2\3\2\11\2\3\1\11\4\3\1\11\1\3\1\11"+
    "\3\3\1\11\4\3\1\11\3\3\1\13\2\11\11\3"+
    "\4\11\3\3\1\11\2\3\1\11\4\3\1\11\1\3"+
    "\1\11\1\3\2\11\7\3\1\11\6\3\2\11\4\3"+
    "\1\11\5\3\1\11\1\3\1\11\4\3\1\11\4\3"+
    "\1\11\1\3\1\11\1\3\2\11\1\3\2\11\2\3"+
    "\2\11\5\3\1\11\3\3\2\11\1\3\1\11\1\3"+
    "\1\11\2\3\1\11\1\3\1\11\1\3\2\11\1\3"+
    "\3\11\1\3\1\11\1\3\1\11\1\3\1\11\1\3"+
    "\1\11\1\3\1\11\2\3\2\11\2\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\114\0\162\0\46\0\230\0\276"+
    "\0\344\0\u010a\0\46\0\u0130\0\u0156\0\u017c\0\46\0\46"+
    "\0\u01a2\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac"+
    "\0\u02d2\0\u02f8\0\u031e\0\u0344\0\u036a\0\u0390\0\u03b6\0\u03dc"+
    "\0\u0402\0\u0428\0\u044e\0\u0474\0\u049a\0\u04c0\0\162\0\u04e6"+
    "\0\u050c\0\u0532\0\u0558\0\u057e\0\u05a4\0\u05ca\0\u05f0\0\u0616"+
    "\0\u063c\0\u063c\0\u0662\0\u017c\0\u0688\0\u06ae\0\u06d4\0\u06fa"+
    "\0\u0720\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de\0\u0804\0\u082a"+
    "\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8\0\u090e\0\u0934\0\u095a"+
    "\0\u0980\0\u09a6\0\u09cc\0\u09f2\0\u0a18\0\u0a3e\0\u090e\0\u0a64"+
    "\0\u0a8a\0\u0ab0\0\u0ad6\0\u0afc\0\u0b22\0\u0b48\0\u0b6e\0\u0b94"+
    "\0\u0bba\0\u0be0\0\u0c06\0\u0c2c\0\u0c52\0\u0c78\0\u0c9e\0\u0cc4"+
    "\0\u0cea\0\u0d10\0\u0c06\0\u0d36\0\u0d5c\0\u0b94\0\u0d82\0\u0da8"+
    "\0\u0dce\0\u0df4\0\u0e1a\0\u0e40\0\u0e66\0\u0e8c\0\u0eb2\0\u0662"+
    "\0\u0ed8\0\u0efe\0\u0f24\0\u0f4a\0\u0c2c\0\u0f70\0\u0f96\0\u0fbc"+
    "\0\u0fe2\0\u1008\0\u102e\0\u1054\0\u0f96\0\u0fbc\0\u107a\0\u10a0"+
    "\0\u10c6\0\u10ec\0\u1112\0\u1138\0\u115e\0\u1184\0\u11aa\0\u11d0"+
    "\0\u11f6\0\u121c\0\u1242\0\u1268\0\u128e\0\u128e\0\u12b4\0\u12da"+
    "\0\u1300\0\u1326\0\u134c\0\u1372\0\u1398\0\u13be\0\u1242\0\u13e4"+
    "\0\u13e4\0\u140a\0\u1430\0\u1456\0\u147c\0\u14a2\0\u14c8\0\u14ee"+
    "\0\u12da\0\u14ee\0\u1514\0\u153a\0\u13be\0\u1560\0\u1586\0\u15ac"+
    "\0\u15d2\0\u15f8\0\u1456\0\u161e\0\u1644\0\u166a\0\u1690\0\u16b6"+
    "\0\u16dc\0\u1702\0\u1728\0\u174e\0\u1774\0\u179a\0\u1728\0\u17c0"+
    "\0\u0eb2\0\u17e6\0\u180c\0\u1832\0\u1832\0\u1858\0\u187e\0\u187e"+
    "\0\u18a4\0\u18ca\0\u166a\0\u18f0\0\u1916\0\u1858\0\u193c\0\u1962"+
    "\0\u174e\0\u1988\0\u19ae\0\u19d4\0\u16dc\0\u19fa\0\u1a20\0\u1a46"+
    "\0\u1a6c\0\344\0\u1a92\0\u1ab8\0\u1ade\0\u1ade\0\u1b04\0\u1b2a"+
    "\0\u1b2a\0\u1a92\0\u1b50\0\u0f70\0\u1b76\0\u1ab8\0\u1b9c\0\u1bc2"+
    "\0\u1be8\0\u1c0e\0\u1c0e\0\u1c34\0\u1c34\0\u0c78\0\u1c5a\0\u1c80"+
    "\0\u1c80\0\u1ca6\0\u1ca6\0\u1ccc\0\u1ccc\0\u1cf2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\14\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\5\1\37"+
    "\1\5\1\40\4\5\50\0\1\4\45\0\2\5\1\0"+
    "\4\5\7\0\26\5\2\0\2\5\1\0\1\41\1\42"+
    "\1\43\1\5\7\0\1\44\1\5\1\45\1\46\1\47"+
    "\1\50\1\5\1\51\1\5\1\52\1\47\1\50\1\47"+
    "\1\53\1\5\1\54\1\55\1\5\1\56\1\57\2\5"+
    "\2\0\2\5\1\0\1\60\1\5\1\60\1\5\7\0"+
    "\26\5\2\0\2\5\1\0\1\47\3\5\7\0\2\5"+
    "\1\47\23\5\2\0\2\5\1\0\1\61\1\5\1\47"+
    "\1\5\7\0\1\62\25\5\12\0\1\14\1\0\1\14"+
    "\31\0\14\63\1\0\31\63\14\64\1\0\31\64\2\0"+
    "\2\5\1\0\1\65\1\42\2\5\7\0\14\5\1\47"+
    "\1\66\10\5\2\0\2\5\1\0\1\67\3\5\7\0"+
    "\2\5\1\70\2\5\1\71\5\5\1\71\12\5\2\0"+
    "\2\5\1\0\1\72\3\5\7\0\11\5\1\72\14\5"+
    "\2\0\2\5\1\0\1\73\1\5\1\47\1\5\7\0"+
    "\2\5\1\74\17\5\1\75\3\5\2\0\2\5\1\0"+
    "\1\76\3\5\7\0\3\5\1\46\14\5\1\55\5\5"+
    "\2\0\2\5\1\0\1\77\3\5\7\0\15\5\1\77"+
    "\10\5\2\0\2\5\1\0\1\100\1\5\1\100\1\5"+
    "\7\0\26\5\2\0\2\5\1\0\1\101\1\5\1\102"+
    "\1\5\7\0\1\103\25\5\2\0\2\5\1\0\1\104"+
    "\1\5\1\104\1\5\7\0\26\5\2\0\2\5\1\0"+
    "\1\105\3\5\7\0\7\5\1\51\5\5\1\106\5\5"+
    "\1\57\2\5\2\0\2\5\1\0\1\107\3\5\7\0"+
    "\3\5\1\46\1\5\1\110\5\5\1\110\4\5\1\55"+
    "\5\5\2\0\2\5\1\0\1\111\3\5\7\0\5\5"+
    "\1\110\5\5\1\110\1\5\1\77\10\5\2\0\2\5"+
    "\1\0\1\112\1\5\1\11\1\5\7\0\5\5\1\113"+
    "\5\5\1\113\3\5\1\54\6\5\2\0\2\5\1\0"+
    "\1\114\3\5\7\0\5\5\1\115\3\5\1\116\1\5"+
    "\1\115\12\5\2\0\2\5\1\0\1\117\3\5\7\0"+
    "\4\5\1\47\5\5\1\47\2\5\1\106\10\5\2\0"+
    "\2\5\1\0\1\120\3\5\7\0\2\5\1\121\17\5"+
    "\1\122\3\5\2\0\2\5\1\0\1\123\1\47\1\124"+
    "\1\125\7\0\1\126\1\127\1\130\1\131\1\132\1\133"+
    "\1\134\1\135\1\5\1\136\1\132\1\133\1\5\1\137"+
    "\5\5\1\140\1\5\1\133\2\0\2\5\1\0\1\127"+
    "\3\5\7\0\1\5\1\127\24\5\2\0\2\5\1\0"+
    "\1\141\1\5\1\124\1\125\7\0\2\5\1\47\12\5"+
    "\1\142\10\5\2\0\2\5\1\0\1\143\1\47\2\5"+
    "\7\0\25\5\1\133\2\0\2\5\1\0\1\144\3\5"+
    "\7\0\1\145\4\5\1\133\5\5\1\133\12\5\2\0"+
    "\2\5\1\0\1\146\3\5\7\0\2\5\1\146\23\5"+
    "\2\0\2\5\1\0\1\147\3\5\7\0\6\5\1\134"+
    "\1\150\5\5\1\151\10\5\2\0\2\5\1\0\1\133"+
    "\3\5\7\0\4\5\1\133\5\5\1\133\13\5\2\0"+
    "\2\5\1\0\1\152\3\5\7\0\3\5\1\153\17\5"+
    "\1\140\2\5\2\0\2\5\1\0\1\154\2\5\1\47"+
    "\7\0\3\5\1\154\22\5\2\0\2\5\1\0\1\51"+
    "\3\5\7\0\7\5\1\51\16\5\2\0\2\5\1\0"+
    "\1\155\3\5\7\0\4\5\1\155\5\5\1\155\13\5"+
    "\2\0\2\5\1\0\1\156\3\5\7\0\1\157\10\5"+
    "\1\136\14\5\2\0\2\5\1\0\1\140\3\5\7\0"+
    "\1\140\25\5\2\0\2\5\1\0\1\125\2\5\1\125"+
    "\7\0\26\5\2\0\2\5\1\0\2\47\2\5\7\0"+
    "\26\5\13\63\1\160\1\0\31\63\2\0\2\5\1\0"+
    "\1\161\3\5\7\0\1\5\1\127\1\5\1\162\22\5"+
    "\2\0\2\5\1\0\1\162\3\5\7\0\3\5\1\162"+
    "\22\5\2\0\2\5\1\0\1\163\3\5\7\0\1\164"+
    "\5\5\1\165\17\5\2\0\2\5\1\0\1\164\3\5"+
    "\7\0\1\164\25\5\2\0\2\5\1\0\1\165\3\5"+
    "\7\0\6\5\1\165\17\5\2\0\2\5\1\0\1\153"+
    "\3\5\7\0\3\5\1\153\22\5\2\0\2\5\1\0"+
    "\1\166\3\5\7\0\5\5\1\133\3\5\1\136\1\5"+
    "\1\133\12\5\2\0\2\5\1\0\1\133\3\5\7\0"+
    "\5\5\1\133\5\5\1\133\12\5\2\0\2\5\1\0"+
    "\1\136\3\5\7\0\11\5\1\136\14\5\2\0\2\5"+
    "\1\0\1\167\3\5\7\0\2\5\1\146\1\5\1\155"+
    "\5\5\1\155\13\5\2\0\2\5\1\0\1\170\3\5"+
    "\7\0\3\5\1\170\22\5\2\0\2\5\1\0\1\171"+
    "\1\5\1\171\1\5\7\0\26\5\2\0\2\5\1\0"+
    "\1\172\1\5\1\173\1\5\7\0\25\5\1\133\2\0"+
    "\2\5\1\0\1\173\1\5\1\173\1\5\7\0\26\5"+
    "\2\0\2\5\1\0\1\133\3\5\7\0\25\5\1\133"+
    "\2\0\2\5\1\0\1\142\3\5\7\0\15\5\1\142"+
    "\10\5\2\0\2\5\1\0\1\174\2\5\1\47\7\0"+
    "\1\140\3\5\1\133\5\5\1\133\13\5\2\0\2\5"+
    "\1\0\1\47\2\5\1\47\7\0\26\5\2\0\2\5"+
    "\1\0\1\175\3\5\7\0\2\5\1\146\1\5\1\155"+
    "\1\5\1\47\3\5\1\155\13\5\2\0\2\5\1\0"+
    "\1\47\3\5\7\0\6\5\1\47\17\5\2\0\2\5"+
    "\1\0\1\176\3\5\7\0\3\5\1\170\2\5\1\47"+
    "\17\5\2\0\2\5\1\0\1\177\3\5\7\0\2\5"+
    "\1\47\4\5\1\51\5\5\1\151\10\5\2\0\2\5"+
    "\1\0\1\151\3\5\7\0\15\5\1\151\10\5\2\0"+
    "\2\5\1\0\1\200\3\5\7\0\7\5\1\150\13\5"+
    "\1\140\2\5\2\0\2\5\1\0\1\150\3\5\7\0"+
    "\7\5\1\150\16\5\2\0\2\5\1\0\1\140\3\5"+
    "\7\0\23\5\1\140\2\5\2\0\2\5\1\0\1\201"+
    "\3\5\7\0\1\201\25\5\2\0\2\5\1\0\1\202"+
    "\3\5\7\0\1\202\25\5\2\0\2\5\1\0\1\157"+
    "\3\5\7\0\1\157\25\5\2\0\2\5\1\0\1\203"+
    "\1\5\1\204\1\5\7\0\1\205\1\47\1\5\1\206"+
    "\1\207\1\210\1\5\1\211\1\212\1\213\1\207\1\210"+
    "\1\5\1\47\6\5\1\214\1\5\2\0\2\5\1\0"+
    "\1\215\3\5\7\0\1\5\1\47\5\5\1\216\16\5"+
    "\2\0\2\5\1\0\1\157\3\5\7\0\5\5\1\157"+
    "\5\5\1\157\12\5\2\0\2\5\1\0\1\217\3\5"+
    "\7\0\3\5\1\220\3\5\1\133\14\5\1\214\1\5"+
    "\2\0\2\5\1\0\1\204\1\5\1\204\1\5\7\0"+
    "\26\5\2\0\2\5\1\0\1\221\3\5\7\0\1\222"+
    "\4\5\1\223\5\5\1\223\12\5\2\0\2\5\1\0"+
    "\1\224\3\5\7\0\1\225\4\5\1\226\3\5\1\227"+
    "\1\5\1\226\12\5\2\0\2\5\1\0\1\230\3\5"+
    "\7\0\3\5\1\231\5\5\1\47\14\5\2\0\2\5"+
    "\1\0\1\47\3\5\7\0\11\5\1\47\14\5\2\0"+
    "\2\5\1\0\1\232\3\5\7\0\7\5\1\232\16\5"+
    "\2\0\2\5\1\0\1\233\3\5\7\0\4\5\1\133"+
    "\2\5\1\234\2\5\1\133\13\5\2\0\2\5\1\0"+
    "\1\47\3\5\7\0\15\5\1\47\10\5\2\0\2\5"+
    "\1\0\1\235\3\5\7\0\4\5\1\236\3\5\1\212"+
    "\1\5\1\236\13\5\2\0\2\5\1\0\1\47\3\5"+
    "\7\0\3\5\1\47\22\5\2\0\2\5\1\0\1\237"+
    "\3\5\7\0\1\5\1\47\2\5\1\236\1\157\1\5"+
    "\1\216\2\5\1\236\1\157\12\5\2\0\2\5\1\0"+
    "\1\236\3\5\7\0\4\5\1\236\5\5\1\236\13\5"+
    "\2\0\2\5\1\0\1\240\3\5\7\0\3\5\1\241"+
    "\5\5\1\47\12\5\1\214\1\5\2\0\2\5\1\0"+
    "\1\242\3\5\7\0\3\5\1\241\20\5\1\214\1\5"+
    "\2\0\2\5\1\0\1\243\3\5\7\0\7\5\1\244"+
    "\1\212\15\5\2\0\2\5\1\0\1\234\3\5\7\0"+
    "\7\5\1\234\16\5\2\0\2\5\1\0\1\212\3\5"+
    "\7\0\10\5\1\212\15\5\2\0\2\5\1\0\1\245"+
    "\3\5\7\0\3\5\1\47\1\5\1\226\5\5\1\226"+
    "\12\5\2\0\2\5\1\0\1\226\3\5\7\0\5\5"+
    "\1\226\5\5\1\226\12\5\2\0\2\5\1\0\1\246"+
    "\3\5\7\0\1\225\10\5\1\227\14\5\2\0\2\5"+
    "\1\0\1\231\3\5\7\0\3\5\1\231\22\5\2\0"+
    "\2\5\1\0\1\143\3\5\7\0\7\5\1\133\5\5"+
    "\1\47\10\5\2\0\2\5\1\0\1\133\3\5\7\0"+
    "\7\5\1\133\16\5\2\0\2\5\1\0\1\247\1\5"+
    "\1\204\1\5\7\0\11\5\1\227\14\5\2\0\2\5"+
    "\1\0\1\227\3\5\7\0\11\5\1\227\14\5\2\0"+
    "\2\5\1\0\1\250\3\5\7\0\7\5\1\232\14\5"+
    "\1\214\1\5\2\0\2\5\1\0\1\214\3\5\7\0"+
    "\24\5\1\214\1\5\2\0\2\5\1\0\1\47\3\5"+
    "\7\0\11\5\1\47\3\5\1\47\10\5\2\0\2\5"+
    "\1\0\1\251\3\5\7\0\1\222\2\5\1\231\1\5"+
    "\1\223\5\5\1\223\12\5\2\0\2\5\1\0\1\225"+
    "\3\5\7\0\1\225\25\5\2\0\2\5\1\0\1\216"+
    "\3\5\7\0\7\5\1\216\16\5\2\0\2\5\1\0"+
    "\1\47\3\5\7\0\1\5\1\47\7\5\1\47\14\5"+
    "\2\0\2\5\1\0\1\47\3\5\7\0\1\5\1\47"+
    "\24\5\2\0\2\5\1\0\1\47\3\5\7\0\3\5"+
    "\1\47\5\5\1\47\14\5\2\0\2\5\1\0\1\252"+
    "\3\5\7\0\4\5\1\133\3\5\1\212\1\5\1\133"+
    "\13\5\2\0\2\5\1\0\1\253\3\5\7\0\3\5"+
    "\1\47\3\5\1\234\16\5\2\0\2\5\1\0\1\254"+
    "\3\5\7\0\3\5\1\241\3\5\1\133\16\5\2\0"+
    "\2\5\1\0\1\241\3\5\7\0\3\5\1\241\22\5"+
    "\2\0\2\5\1\0\1\255\1\256\1\157\1\5\7\0"+
    "\1\257\1\5\1\260\1\261\3\5\1\143\1\140\1\262"+
    "\3\5\1\263\1\264\1\265\6\5\2\0\2\5\1\0"+
    "\1\266\3\5\7\0\2\5\1\266\23\5\2\0\2\5"+
    "\1\0\1\267\3\5\7\0\7\5\1\47\5\5\1\263"+
    "\10\5\2\0\2\5\1\0\1\270\3\5\7\0\11\5"+
    "\1\270\14\5\2\0\2\5\1\0\1\271\1\5\1\157"+
    "\1\5\7\0\11\5\1\47\14\5\2\0\2\5\1\0"+
    "\1\272\3\5\7\0\2\5\1\136\4\5\1\133\1\140"+
    "\15\5\2\0\2\5\1\0\1\273\1\256\2\5\7\0"+
    "\1\257\10\5\1\274\14\5\2\0\2\5\1\0\1\261"+
    "\3\5\7\0\3\5\1\261\22\5\2\0\2\5\1\0"+
    "\1\264\3\5\7\0\16\5\1\264\7\5\2\0\2\5"+
    "\1\0\1\265\3\5\7\0\17\5\1\265\6\5\2\0"+
    "\2\5\1\0\1\275\3\5\7\0\11\5\1\275\14\5"+
    "\2\0\2\5\1\0\1\276\3\5\7\0\11\5\1\277"+
    "\5\5\1\265\6\5\2\0\2\5\1\0\1\300\3\5"+
    "\7\0\11\5\1\300\14\5\2\0\2\5\1\0\1\301"+
    "\3\5\7\0\10\5\1\140\4\5\1\263\10\5\2\0"+
    "\2\5\1\0\1\263\3\5\7\0\15\5\1\263\10\5"+
    "\2\0\2\5\1\0\1\140\3\5\7\0\10\5\1\140"+
    "\15\5\2\0\2\5\1\0\1\302\3\5\7\0\2\5"+
    "\1\136\4\5\1\47\6\5\1\264\7\5\2\0\2\5"+
    "\1\0\1\47\3\5\7\0\7\5\1\47\16\5\2\0"+
    "\2\5\1\0\1\136\3\5\7\0\2\5\1\136\23\5"+
    "\2\0\2\5\1\0\1\62\3\5\7\0\11\5\1\62"+
    "\14\5\2\0\2\5\1\0\1\257\3\5\7\0\1\257"+
    "\25\5\2\0\2\5\1\0\1\303\1\256\2\5\7\0"+
    "\11\5\1\47\14\5\2\0\2\5\1\0\2\256\2\5"+
    "\7\0\26\5\2\0\2\5\1\0\1\304\1\5\1\157"+
    "\1\5\7\0\3\5\1\261\22\5\2\0\2\5\1\0"+
    "\1\157\1\5\1\157\1\5\7\0\26\5\2\0\2\5"+
    "\1\0\1\305\1\5\1\157\1\5\7\0\7\5\1\133"+
    "\1\5\1\275\14\5\2\0\2\5\1\0\1\306\3\5"+
    "\7\0\11\5\1\300\5\5\1\265\6\5\2\0\2\5"+
    "\1\0\1\307\1\256\2\5\7\0\1\257\2\5\1\261"+
    "\22\5\2\0\2\5\1\0\1\310\1\256\2\5\7\0"+
    "\1\257\25\5\2\0\2\5\1\0\1\311\3\5\7\0"+
    "\7\5\1\47\6\5\1\264\7\5\2\0\2\5\1\0"+
    "\1\312\3\5\7\0\2\5\1\266\13\5\1\264\7\5"+
    "\2\0\2\5\1\0\1\313\3\5\7\0\1\257\16\5"+
    "\1\265\6\5\2\0\2\5\1\0\1\314\3\5\7\0"+
    "\10\5\1\140\1\62\3\5\1\263\10\5\2\0\2\5"+
    "\1\0\1\315\3\5\7\0\3\5\1\261\5\5\1\47"+
    "\14\5\2\0\2\5\1\0\1\277\3\5\7\0\11\5"+
    "\1\277\14\5\2\0\2\5\1\0\1\316\1\47\2\5"+
    "\7\0\1\317\2\5\1\320\3\5\1\321\1\47\1\322"+
    "\3\5\2\47\1\323\6\5\2\0\2\5\1\0\1\324"+
    "\3\5\7\0\17\5\1\324\6\5\2\0\2\5\1\0"+
    "\1\47\3\5\7\0\10\5\1\47\15\5\2\0\2\5"+
    "\1\0\1\325\3\5\7\0\3\5\1\326\11\5\1\47"+
    "\10\5\2\0\2\5\1\0\1\317\3\5\7\0\1\317"+
    "\25\5\2\0\2\5\1\0\1\327\1\47\2\5\7\0"+
    "\7\5\1\330\7\5\1\136\6\5\2\0\2\5\1\0"+
    "\1\47\3\5\7\0\16\5\1\47\7\5\2\0\2\5"+
    "\1\0\1\11\3\5\7\0\11\5\1\11\14\5\2\0"+
    "\2\5\1\0\1\133\3\5\7\0\3\5\1\133\22\5"+
    "\2\0\2\5\1\0\1\326\3\5\7\0\3\5\1\326"+
    "\22\5\2\0\2\5\1\0\1\331\1\47\2\5\7\0"+
    "\7\5\1\330\16\5\2\0\2\5\1\0\1\47\3\5"+
    "\7\0\3\5\1\47\5\5\1\47\3\5\1\47\10\5"+
    "\2\0\2\5\1\0\1\332\3\5\7\0\10\5\1\47"+
    "\6\5\1\323\6\5\2\0\2\5\1\0\1\136\3\5"+
    "\7\0\17\5\1\136\6\5\2\0\2\5\1\0\1\321"+
    "\3\5\7\0\3\5\1\133\3\5\1\330\16\5\2\0"+
    "\2\5\1\0\1\330\3\5\7\0\7\5\1\330\16\5"+
    "\2\0\2\5\1\0\1\47\3\5\7\0\3\5\1\47"+
    "\12\5\1\47\7\5\2\0\2\5\1\0\1\322\3\5"+
    "\7\0\11\5\1\11\3\5\1\47\10\5\2\0\2\5"+
    "\1\0\1\333\3\5\7\0\1\317\6\5\1\133\16\5"+
    "\2\0\2\5\1\0\1\334\3\5\7\0\7\5\1\133"+
    "\1\5\1\47\5\5\1\136\6\5\2\0\2\5\1\0"+
    "\1\335\3\5\7\0\1\317\7\5\1\47\6\5\1\324"+
    "\6\5\2\0\2\5\1\0\1\336\3\5\7\0\10\5"+
    "\1\47\6\5\1\324\6\5\2\0\2\5\1\0\1\337"+
    "\3\5\7\0\3\5\1\326\5\5\1\11\14\5\2\0"+
    "\2\5\1\0\1\143\3\5\7\0\3\5\1\133\4\5"+
    "\1\47\15\5\2\0\2\5\1\0\2\47\2\5\7\0"+
    "\3\5\1\47\12\5\1\47\7\5\2\0\2\5\1\0"+
    "\1\340\1\5\1\136\1\5\7\0\1\341\1\5\1\47"+
    "\1\5\1\47\4\5\2\47\2\5\1\47\10\5\2\0"+
    "\2\5\1\0\1\136\1\5\1\136\1\5\7\0\26\5"+
    "\2\0\2\5\1\0\1\47\3\5\7\0\4\5\1\47"+
    "\4\5\2\47\13\5\2\0\2\5\1\0\1\342\3\5"+
    "\7\0\1\343\10\5\1\47\14\5\2\0\2\5\1\0"+
    "\1\344\3\5\7\0\1\345\14\5\1\47\10\5\2\0"+
    "\2\5\1\0\1\345\3\5\7\0\1\345\25\5\2\0"+
    "\2\5\1\0\1\47\3\5\7\0\4\5\1\47\5\5"+
    "\1\47\13\5\2\0\2\5\1\0\1\342\3\5\7\0"+
    "\1\343\14\5\1\47\10\5\2\0\2\5\1\0\1\343"+
    "\3\5\7\0\1\343\25\5\2\0\2\5\1\0\1\346"+
    "\1\5\1\136\1\5\7\0\11\5\1\47\14\5\2\0"+
    "\2\5\1\0\1\347\1\5\1\136\1\5\7\0\1\345"+
    "\25\5\2\0\2\5\1\0\1\47\3\5\7\0\2\5"+
    "\1\47\1\5\1\47\5\5\1\47\13\5\2\0\2\5"+
    "\1\0\1\350\3\5\7\0\15\5\1\350\10\5\2\0"+
    "\2\5\1\0\1\351\3\5\7\0\15\5\1\351\10\5"+
    "\2\0\2\5\1\0\1\133\3\5\7\0\15\5\1\133"+
    "\10\5\2\0\2\5\1\0\1\352\3\5\7\0\15\5"+
    "\1\352\10\5\2\0\2\5\1\0\1\353\3\5\7\0"+
    "\15\5\1\353\10\5\2\0\2\5\1\0\1\354\3\5"+
    "\7\0\4\5\1\355\4\5\1\47\1\355\13\5\2\0"+
    "\2\5\1\0\1\355\3\5\7\0\4\5\1\355\5\5"+
    "\1\355\13\5\2\0\2\5\1\0\1\356\3\5\7\0"+
    "\3\5\1\356\22\5\2\0\2\5\1\0\1\173\3\5"+
    "\7\0\11\5\1\173\14\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7448];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\4\1\1\11\3\1\2\11"+
    "\42\1\1\0\273\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[238];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Sintactico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Analizador_Sintactico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 4: 
          { if(yytext().equals(">=")){return new Symbol(sym.mayorigual, yychar, yyline, yytext());}
                                        if(yytext().equals("<=")){return new Symbol(sym.menorigual, yychar, yyline, yytext());}
                                        if(yytext().equals("=")){return new Symbol(sym.igual, yychar, yyline, yytext());}
                                        if(yytext().equals(">")){return new Symbol(sym.mayor, yychar, yyline, yytext());}
                                        if(yytext().equals("<")){return new Symbol(sym.menor, yychar, yyline, yytext());}
          }
        case 12: break;
        case 9: 
          { if(yytext().equalsIgnoreCase("if")){return new Symbol(sym.if_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("imports")){return new Symbol(sym.imports, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("public")){return new Symbol(sym.public_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("module")){return new Symbol(sym.module, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("sub")){return new Symbol(sym.sub, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("for")){return new Symbol(sym.for_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("dim")){return new Symbol(sym.dim, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("end")){return new Symbol(sym.end_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("integer")){return new Symbol(sym.integer_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("boolean")){return new Symbol(sym.boolean_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("string")){return new Symbol(sym.string_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("system")){return new Symbol(sym.system_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("console")){return new Symbol(sym.console_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("writeline")){return new Symbol(sym.writeline, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("as")){return new Symbol(sym.as, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("do")){return new Symbol(sym.do_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("while")){return new Symbol(sym.while_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("struct")){return new Symbol(sym.struct_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("then")){return new Symbol(sym.then, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("else")){return new Symbol(sym.else_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("function")){return new Symbol(sym.function_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("return")){return new Symbol(sym.return_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("next")){return new Symbol(sym.next, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("private")){return new Symbol(sym.private_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("loop")){return new Symbol(sym.loop, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("exit")){return new Symbol(sym.exit, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("until")){return new Symbol(sym.until, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("to")){return new Symbol(sym.to, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("and")){return new Symbol(sym.and, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("or")){return new Symbol(sym.or, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("true")){return new Symbol(sym.true_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("false")){return new Symbol(sym.false_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("like")){return new Symbol(sym.like, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("mod")){return new Symbol(sym.mod, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("int")){return new Symbol(sym.int_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("null")){return new Symbol(sym.null_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("main")){return new Symbol(sym.main_, yychar, yyline, yytext());}
                                        if(yytext().equalsIgnoreCase("step")){return new Symbol(sym.step_, yychar, yyline, yytext());}
          }
        case 13: break;
        case 2: 
          { return new Symbol(sym.numero, yychar, yyline, yytext());
          }
        case 14: break;
        case 1: 
          { return new Symbol(sym.error, yychar, yyline, yytext());
          }
        case 15: break;
        case 8: 
          { return new Symbol(sym.continuaciondelinea, yychar, yyline, yytext());
          }
        case 16: break;
        case 7: 
          { if(yytext().equals(".")){return new Symbol(sym.punto, yychar, yyline, yytext());}
                                        if(yytext().equals("\"")){return new Symbol(sym.comillaD, yychar, yyline, yytext());}
                                        if(yytext().equals("\'")){return new Symbol(sym.comillaS, yychar, yyline, yytext());}
                                        if(yytext().equals("(")){return new Symbol(sym.parentesisA, yychar, yyline, yytext());}
                                        if(yytext().equals(")")){return new Symbol(sym.parentesisC, yychar, yyline, yytext());}
                                        if(yytext().equals("{")){return new Symbol(sym.llaveA, yychar, yyline, yytext());}
                                        if(yytext().equals("}")){return new Symbol(sym.llaveC, yychar, yyline, yytext());}
                                        if(yytext().equals(",")){return new Symbol(sym.coma, yychar, yyline, yytext());}
          }
        case 17: break;
        case 5: 
          { if(yytext().equals("+")){return new Symbol(sym.suma, yychar, yyline, yytext());}
                                        if(yytext().equals("-")){return new Symbol(sym.resta, yychar, yyline, yytext());}
                                        if(yytext().equals("*")){return new Symbol(sym.mult, yychar, yyline, yytext());}
                                        if(yytext().equals("/")){return new Symbol(sym.div, yychar, yyline, yytext());}
                                        if(yytext().equals("^")){return new Symbol(sym.potencia, yychar, yyline, yytext());}
          }
        case 18: break;
        case 3: 
          { return new Symbol(sym.identificador, yychar, yyline, yytext());
          }
        case 19: break;
        case 11: 
          { return new Symbol(sym.texto_, yychar, yyline, yytext());
          }
        case 20: break;
        case 10: 
          { return new Symbol(sym.comentario, yychar, yyline, yytext());
          }
        case 21: break;
        case 6: 
          { return new Symbol(sym.espacio, yychar, yyline, yytext());
          }
        case 22: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
