
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 16 22:46:22 CST 2021
//----------------------------------------------------

package proyectocompiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int dim = 8;
  public static final int resta = 46;
  public static final int suma = 45;
  public static final int loop = 26;
  public static final int exit = 27;
  public static final int next = 24;
  public static final int end_ = 9;
  public static final int mod = 35;
  public static final int integer_ = 10;
  public static final int as = 16;
  public static final int imports = 2;
  public static final int false_ = 33;
  public static final int null_ = 38;
  public static final int coma_ = 66;
  public static final int like = 34;
  public static final int do_ = 17;
  public static final int igual = 42;
  public static final int identificador = 39;
  public static final int mod_ = 70;
  public static final int until = 28;
  public static final int writeline = 15;
  public static final int private_ = 25;
  public static final int byval = 68;
  public static final int console_ = 14;
  public static final int else_ = 21;
  public static final int numero = 51;
  public static final int then = 20;
  public static final int menor = 44;
  public static final int sub = 6;
  public static final int EOF = 0;
  public static final int int_ = 36;
  public static final int System_ = 13;
  public static final int error = 1;
  public static final int elseif_ = 69;
  public static final int true_ = 32;
  public static final int mayor = 43;
  public static final int if_ = 3;
  public static final int Module = 5;
  public static final int or = 31;
  public static final int function_ = 22;
  public static final int menorigual = 41;
  public static final int while_ = 18;
  public static final int return_ = 23;
  public static final int punto = 54;
  public static final int Public_ = 4;
  public static final int error_ = 67;
  public static final int llaveC = 60;
  public static final int potencia = 49;
  public static final int struct_ = 19;
  public static final int llaveA = 59;
  public static final int string_ = 12;
  public static final int findelinea = 62;
  public static final int mult = 47;
  public static final int mayorigual = 40;
  public static final int guionB = 61;
  public static final int continuaciondelinea = 63;
  public static final int and = 30;
  public static final int for_ = 7;
  public static final int texto_ = 50;
  public static final int comillaS = 56;
  public static final int comentario = 64;
  public static final int parentesisC = 58;
  public static final int parentesisA = 57;
  public static final int espacio = 52;
  public static final int step_ = 37;
  public static final int div = 48;
  public static final int main_ = 65;
  public static final int modulo = 53;
  public static final int to = 29;
  public static final int comillaD = 55;
  public static final int boolean_ = 11;
}

